# Generated by Django 4.0.4 on 2022-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('steam', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('game', models.TextField(choices=[('PUBG', 'Player’s Unknown Battle Ground'), ('FORT', 'Fortnite Battle Royale'), ('APEX', 'Apex Legends'), ('LOL', 'Leauge of Legends'), ('CSGO', 'Counter Strike: Global Offensive'), ('HEART', 'Heartstone'), ('MINE', 'Minecraft'), ('DOTA', 'DOTA  2'), ('DIV', 'The Division 2'), ('SPLAT', 'The Splatoon 2')])),
            ],
        ),
    ]
