# Generated by Django 4.0.4 on 2022-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='callback',
            field=models.CharField(default='start_context', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.TextField(choices=[('PUBG', 'Player’s Unknown Battle Ground'), ('FORT', 'Fortnite Battle Royale'), ('APEX', 'Apex Legends'), ('LOL', 'League of Legends'), ('CSGO', 'Counter Strike: Global Offensive'), ('HEART', 'Heartstone'), ('MINE', 'Minecraft'), ('DOTA', 'DOTA  2'), ('DIV', 'The Division 2'), ('SPLAT', 'The Splatoon 2')]),
        ),
    ]
