# Generated by Django 4.0.4 on 2022-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_player_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.IntegerField(default=9999999),
        ),
    ]
