# Generated by Django 4.0.4 on 2022-04-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='chat_id',
        ),
    ]
